version: "{build}"

image: Visual Studio 2017

environment:
  matrix:
    - NODEJS_VERSION: "6"
      BROWSER: chrome
    - NODEJS_VERSION: "7"
      BROWSER: firefox
    - NODEJS_VERSION: "8"
      BROWSER: chrome-headless
    - NODEJS_VERSION: "8"
      BROWSER: phantomjs

cache:
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
