jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: Chrome
    vmImage: 'ubuntu-16.04'
    nodeVersion: '8.x'
    browser: firefox

- template: azure-pipelines-template.yml
  parameters:
    name: Safari
    vmImage: 'macOS-10.13'
    nodeVersion: '9.x'
    browser: chrome-headless

- template: azure-pipelines-template.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    nodeVersion: '10.x'
    browser: internet-explorer
