parameters:
  name: ''
  vmImage: ''
  nodeVersion: ''
  browser: ''
  preBuild: []
  multipleSessionsAllowed: true

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: CodeCheck
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: Install Node.js

  - ${{ parameters.preBuild }}

  - script: npm install
    displayName: Install dependencies
    workingDirectory: $(coreDirectory)

  - script: npm test -- --ci
    condition: eq(variables['multipleSessionsAllowed'], 'true')
    displayName: Test with multiple Sessions
    workingDirectory: $(coreDirectory)
    env:
      BROWSER: ${{ parameters.browser }}
      BROWSERSTACK_USERNAME: $(browserstack.user)
      BROWSERSTACK_ACCESS_KEY: $(browserstack.key)

  - script: npm test -- --ci --runInBand
    condition: eq(variables['multipleSessionsAllowed'], 'false')
    displayName: Test with single Session
    workingDirectory: $(coreDirectory)
    env:
      BROWSER: ${{ parameters.browser }}
      BROWSERSTACK_USERNAME: $(browserstack.user)
      BROWSERSTACK_ACCESS_KEY: $(browserstack.key)
