parameters:
  name: ''
  vmImage: ''
  nodeVersion: ''
  browser: ''
  preBuild: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    BROWSER: ${{ parameters.browser }}
    BROWSERSTACK_USERNAME: $(browserstack.user)
    BROWSERSTACK_ACCESS_KEY: $(browserstack.key)
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: Install Node.js

  - ${{ parameters.preBuild }}

  - script: npm install
    displayName: Install dependencies
    workingDirectory: $(coreDirectory)

  - script: npm run lint
    displayName: Lint
    workingDirectory: $(coreDirectory)

  - script: npm test -- --ci --runInBand
    displayName: Test
    workingDirectory: $(coreDirectory)
